arm64/neon: Disable -Wincompatible-pointer-types when building with Clang
This silences the following compilation error:

arch/arm64/lib/xor-neon.c:58:28: error: incompatible pointer types
assigning to 'const unsigned long *' from 'uint64_t *' (aka 'unsigned
long long *') [-Werror,-Wincompatible-pointer-types]
                v3 = veorq_u64(vld1q_u64(dp1 +  6), vld1q_u64(dp2 + 6));
                                         ^~~~~~~~
/usr/lib/llvm-9/lib/clang/9.0.0/include/arm_neon.h:7538:47: note:
expanded from macro 'vld1q_u64'
  __ret = (uint64x2_t) __builtin_neon_vld1q_v(__p0, 51); \
                                              ^~~~

Based on ClangBuiltLinux/linux@0738c8b, we do not have the
framework supporting CONFIG_CC_IS_CLANG on 4.14 so we'll take an
alternative approach to disabling this warning when NEON
accelerated XOR is in use.

Signed-off-by: Adam W. Willis <return.of.octobot@gmail.com>
Signed-off-by: mawrick26 <mawrick26@gmail.com>